# Generated by Django 3.1.5 on 2021-04-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('no', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='birth_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='df',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='perc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='tf',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.course'),
        ),
    ]
